### PR TITLE
New Golang container images

### PR DESCRIPTION
**Pull request by mvarlese**

### CODE REVIEW

**Review by dcermak — APPROVED** [review]

**Review by dcermak — DISMISSED** [review]
The containers no longer include `make`, which breaks the test suite.

**Comment by mvarlese** [comment]
> The containers no longer include `make`, which breaks the test suite.

Yes, fix on its way. Hold tight :)

**Comment by evrardjp** [comment]
> Yes, fix on its way. Hold tight :)

https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpics.me.me%2Fhold-on-to-your-butts-9822482.png&f=1&nofb=1

**Comment by evrardjp** [comment]
Azure apt mirror b0rked , need retriggering tests.

**Review by evrardjp — APPROVED** [review]
LGTM

**Pull request merged**
